# If PPPoE is running inside LXC container, we should setup kernel module loading
# on host system instead of inside container.
# Put host name inside "lxc_container" group in ansible inventory to mark this.
- include_tasks: kernel-module.yml
  when: "'pppoe' in group_names and 'lxc_container' not in group_names"

- meta: end_host
  when: "'pve_host' in group_names"

- name: install package on system
  include: "{{ router_os_distribution }}-pkg.yml"

- name: generate pppoe peer config under /etc/ppp/peers
  include_tasks: interface.yml
  loop: "{{ pppoe_provider | dict2items }}"
  register: pppoe_provider
  tags:
    - config

- name: generate ppp hook scripts
  template: src={{ item }} dest=/{{ item | regex_replace('\.j2$', '') }} owner=root group=root mode="0755"
  with_items:
    - etc/ppp/ip-up.d/00-dns.sh.j2
    - etc/ppp/ip-down.d/00-dns.sh.j2
  tags:
    - config
